version: "3.8"
services:
  apache:
    container_name: apache
    build: ./docker/apache
    links:
      - php
    ports:
      - "80:80"
    volumes:
      - ./m2:/usr/local/apache2/htdocs
  php:
    container_name: php
    build: ./docker/php
    links:
      - mysql
    ports:
      - "9000:9000"
    volumes:
      - ./m2:/usr/local/apache2/htdocs
    working_dir: /usr/local/apache2/htdocs
  mysql:
    image: mysql:8.0.27
    container_name: mysql
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'test'
      MYSQL_DATABASE: magento
      MYSQL_USER: root
      MYSQL_PASSWORD: 'test'
    ports:
      - "3306:3306"
    volumes:
    - ./database/mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8085:80
  mailhog:
   image: mailhog/mailhog
   container_name: mailhog
   hostname: mailhog
   ports:
      - "1025:1025"
      - "8025:8025"
  es7.9:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: es7.9
    hostname: es7.9
    environment:
      - node.name=es7.9
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
